app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['as'=>'home', 'before'=>'already.log', 'uses'=>'UsersController@login']);
Route::get('termos-e-condicoes', ['as'=>'site.terms', 'uses'=>'SiteController@terms']);

# Usuários
Route::get('cadastro', ['as'=>'users.create', 'before'=>'already.log', 'uses'=>'UsersController@create']);
Route::post('cadastro', ['as'=>'users.store', 'before'=>'already.log', 'uses'=>'UsersController@store']);
Route::post('upload/image', ['as'=>'users.upload.image', 'before'=>'already.log', 'uses'=>'UsersController@uploadImage']);

Route::get('cadastro/participante', ['as'=>'guests.create', 'before'=>'already.log', 'uses'=>'UsersController@create']);



Route::get('cadastro/confirmacao/{activationCode}', ['as'=>'user.register.activation', 'uses'=>'UsersController@activation']);

# Login
Route::get('login', ['as'=>'user.login', 'before'=>'already.log', 'uses'=>'UsersController@login']);
Route::post('login', ['as'=>'user.post.login', 'uses'=>'UsersController@postLogin']);

# Passwords
Route::get('password/reset', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('password/reset/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);



# Searches
Route::post('city/search', ['as'=>'city.search', 'uses'=>'CitiesController@searchByState']);


Route::group(['before'=>'auth'], function(){

	#Retono do cadastro com o usário logaodo
	Route::get('cadastro/finalizado', ['as'=>'users.register.return', 'uses'=>'UsersController@registerReturn']);

	Route::get('lideres', ['as'=>'institutes.leaders', 'uses'=>'UsersController@indexApp']);

	# Usuarios
	Route::get('editar', ['as' => 'user.front.edit', 'uses'=>'UsersController@frontEdit']);
	Route::put('editar/{id}', ['as' => 'user.front.update', 'uses'=>'UsersController@frontUpdate']);
	Route::put('editar/pass/{id}', ['as' => 'user.update.password', 'uses'=>'UsersController@updatePass']);
	Route::get('group/edit', ['as' => 'user.update.group', 'uses'=>'UsersController@updateGroup']);


	# Agendamento
	Route::get('agendamento/concluido', ['as'=>'agendamento.confirmed', 'uses'=>'AgendasController@resp']);
	Route::get('agendamento/{institute_id?}', ['as'=>'agendamento.create', 'before'=>'colaborator.access', 'uses'=>'AgendasController@create']);
	Route::post('agendamento', ['as'=>'agendamento.store',  'uses'=>'AgendasController@store']);


	Route::get('agendas', ['as'=>'agendamento.index', 'before'=>'colaborator.access', 'uses'=>'AgendasController@indexApp']);
	
	Route::get('logout', ['as'=>'user.logout', 'uses' => 'UsersController@logout']);

	# Materiais Promocionais
	Route::get('material-de-apoio', ['as'=>'materials.index', 'before'=>'colaborator.access', 'uses'=>'MaterialsController@indexApp']);
});

# Admin Geral
Route::get('admin', ['as'=>'admin.index', 'before'=>'already.log.admin', 'uses'=>'AdminController@index']);
Route::post('admin/login',['as'=>'admin.login', 'uses'=>'AdminController@login']);

# Acao de baixa relatóio
	Route::post('usuarios/download/relatorio', ['as'=>'user.download.excel', 'uses'=>'UsersController@download']);

Route::group(['prefix'=>'admin', 'before'=>'auth|auth.admin'], function(){

	# Institutos
	Route::resource('institutos', 'InstitutesController');

	# Materials
	Route::resource('materiais', 'MaterialsController');

	# Agendas
	Route::post('agendas/download/relatorio', ['as'=>'agenda.download.excel', 'uses'=>'AgendasController@download']);
	Route::post('agendas/acao', ['as'=>'agenda.action', 'uses'=>'AgendasController@action']);
	Route::get('agendas/buscar', ['as'=>'agenda.search', 'uses'=>'AgendasController@index']);

	# Ações com pos-visita
	Route::get('pos-visitas/agenda/{agenda_id}/mostrar', ['as'=>'admin.visiters.show', 'uses'=>'AgendasController@showVisiters']);
	

	Route::resource('agendas', 'AgendasController');
	//Route::get('agendas/realizadas', ['as'=>'admin.agendas.realizadas','uses'=>'AgendasController@agendasRealizadas']);
	

	# Líderes/usuários
	Route::get('usuarios/participantes', ['as'=>'admin.usuarios.guests', 'uses'=>'UsersController@guests']);
	Route::get('usuarios/buscar', ['as'=>'users.search', 'uses'=>'UsersController@index']);

	Route::resource('usuarios', 'UsersController');

	# Usuarios administrativos
	Route::get('administrativos/usuarios', ['as'=>'admin.users','uses'=>'AdminController@indexAdmin']);
	Route::post('administrativos/usuarios', ['as'=>'admin.users.create','uses'=>'AdminController@indexAdminCreate']);
	Route::delete('administrativos/usuarios/{id}', ['as'=>'admin.users.delete','uses'=>'AdminController@deleteAdminUser']);

	# Logout
	Route::get('logout', ['as'=>'admin.logout', 'uses'=>'AdminController@logout']);

	#Pos visitas
	Route::get('pos-visitas/agenda/{agenda_id}/mostrar', ['as'=>'admin.visiters.show', 'uses'=>'AgendasController@showVisiters']);
	
	# Trasferencia de agendamento
	Route::post('agendamento/transferir/{agenda}', ['as'=>'admin.agenda.transfer', 'uses'=>'AgendasController@transfer']);
	
	# Relatórios
	Route::get('relatorios/conversoes', ['as'=>'admin.relatorios.conversion', 'uses'=>'AdminController@conversion']);
	Route::post('relatorios/conversoes', ['as'=>'admin.relatorios.conversion.post', 'uses'=>'AdminController@conversion']);
	Route::post('relatorios/pos-visitas', ['as'=>'admin.relatorios.posvisitas', 'uses'=>'AdminController@excelPosVisita']);

	Route::any('relatorios/consolidado', ['as'=>'relatorio.all', 'uses'=>'AdminController@relatorioAll']);

});

# Admin GCs
Route::group(['prefix'=>'instituto', 'before'=>'auth|auth.manager'], function(){
	// Agrupando o instituto em si
	Route::group(['prefix'=>'{slug}', 'before'=>'institute.manager'], function($slug){

		# Agendas
		Route::get('agendas', ['as'=>'instituto.agendas.index', 'uses'=>'AgendasController@index']);
		Route::post('agendas/download/relatorio', ['as'=>'instituto.agenda.download.excel', 'uses'=>'AgendasController@download']);
		Route::post('agendas/acao', ['as'=>'instituto.agenda.action', 'uses'=>'AgendasController@action']);
		Route::get('agendas/buscar', ['as'=>'instituto.agenda.search', 'uses'=>'AgendasController@index']);

		# Líderes/usuários
		Route::get('usuarios', ['as'=>'instituto.usuarios.index','uses'=>'UsersController@index']);

		# Pós visita
		Route::get('pos-visitas/pendentes', ['as'=>'visiters.pendentes', 'uses'=>'AgendasController@visiters']);
		Route::get('pos-visitas/realizados', ['as'=>'visiters.realizados', 'uses'=>'AgendasController@visiters']);
		Route::get('pos-visitas/buscar', ['as'=>'visiters.search', 'uses'=>'AgendasController@visiters']);
		Route::get('pos-visitas/agenda/{agenda_id}', ['as'=>'visiters.create', 'uses'=>'AgendasController@createVisiters']);
		
		Route::post('pos-visitas/agenda/{agenda_id}', ['as'=>'visiters.store', 'uses'=>'AgendasController@storeVisiters']);

		# Trasferencia de agendamento
		Route::post('agendamento/transferir/{agenda}', ['as'=>'agenda.transfer', 'uses'=>'AgendasController@transferIns']);

		# Logout
		Route::get('logout', ['as'=>'manager.logout', 'uses'=>'AdminController@managerLogout']);

		# Agendamento Manual
		Route::get('agendamento/manual', ['as'=>'admin.agendamento.create', 'uses'=>'AgendasController@createAgendamento']);
		
	});
	
	# Ações com pos-visita
	Route::get('pos-visitas/agenda/{agenda_id}/mostrar', ['as'=>'visiters.show', 'uses'=>'AgendasController@showVisiters']);
	Route::get('pos-visitas/agenda/{agenda_id}/editar', ['as'=>'visiters.edit', 'uses'=>'AgendasController@showVisiters']);
	Route::post('pos-visitas/agenda/{agenda_id}/update', ['as'=>'visiters.update', 'uses'=>'AgendasController@updateVisiters']);
});

Route::get('instituto/{slug}', ['as'=>'manager.index', 'uses'=>'AdminController@index']);
Route::get('instituto/{slug}/novo-gc', ['as'=>'new.manager', 'uses'=>'AdminController@indexNewManager']);
Route::post('instituto/{slug}/novo-gc', ['as'=>'register.new.manager', 'uses'=>'AdminController@registerNewManager']);


// Validators
Validator::extend('cpf', 'CustomValidator@cpf', 'CPF inválido');

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

	public function userdata(){

		return $this->hasOne('Userdata');
	}

	public function profession(){
		return $this->hasOne('Profession');
	}

	public function manager(){
		return $this->hasOne('Manager');
	}

	public function institutes(){
		return $this->belongsToMany('Institute');
	}

	public function agendas(){
		return $this->hasMany('Agenda')->orderBy('date_marked','DESC');
	}

	public function agendas_posvisita_pendente($institute)
	{
		$agendas = Agenda::where(function($q){
			$q->whereIn('status',['0','1'])->where('date_marked','>',date('Y-m-d'));
		})
		->orWhere(function($q){
			$q->whereStatus('3')->has('visiter','=','0');
		})
		//->whereUser_id($this->id)
		->whereInstitute_id($institute)->get();
		//print_r(DB::getQueryLog());
		return $agendas;

		//->whereOr(function($q){$q->where('date_marked','>',date('Y-m-d'))})
			
		
	}

	public function getImage($url=false)
	{
		$src = 'img/avatar.png';
		if($this->userdata->src != ''){
			$src = 'uploads/'.$this->userdata->src;
		}

		return $url == true ? $src : '<img src="'.$src.'" alt="'.$this->name.'">';
	
	}
	public function scopeGetLeadersNearest($query, $state_id){
		return $query->join('userdatas','users.id', '=', 'userdatas.user_id')
				->join('cities', 'userdatas.city_id', '=', 'cities.id')
				->join('states', 'cities.state_id', '=', 'states.id')
				->where('states.id', $state_id)
				->select('users.*');
	}

	public function scopeGetAgendaInstitute($query, $slug, $realizado=false)
	{
		$query->join('agendas', 'users.id','=','agendas.user_id')
		->join('institutes', 'agendas.institute_id','=','institutes.id');
		if($realizado == true){
			$query->join('visiters', 'agendas.id', '=', 'visiters.agenda_id');
		}
		$query->where('institutes.slug',$slug)
		->orderBy('agendas.id', 'DESC')
		->select('users.*');
	}


	public static function boot(){
		parent::boot();

		static::deleted(function($u)
		{
			$u->userdata()->delete();
			DB::table('users_groups')->whereUser_id($u->id)->delete();
			
		});
	}

}

app/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
           Usuários administrativos <small>({{ $users->getTotal() }})</small>
        </h1>
    </div>
</div>
<!-- /.row -->
<div class="row" id="searchBlock">
	<div class="col-md-10">
		{{ Form::open(['route'=>'admin.users.create']) }}
		
		{{ Form::text('username', null, ['class'=>'form-group','placeholder'=>'Nome']) }}
		{{ Form::email('email', null, ['class'=>'form-group','placeholder'=>'Email']) }}
		{{ Form::password('password', ['class'=>'form-group','placeholder'=>'Senha']) }}
		{{ Form::password('password_confirmation', ['class'=>'form-group','placeholder'=>'Confirmar Senha']) }}

		{{ Form::button('Criar novo', ['class'=>'btn btn-primary','type'=>'submit']) }}
		{{ Form::close() }}
	</div>
</div>
<div class="col-md-12">
	
	@include('layouts.notifications')
	
	@if($users->count() > 0)
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
			<tr>
				<th>Nome</th>
				<th>Email</th>
				<th>Apagar</th>
				
			</tr>
			@foreach($users as $user)
				<tr>
					<td>{{ $user->userdata->username }}</td>
					<td>{{ $user->email }}</td>
					<td>
						{{ Form::open(['route'=>array('admin.users.delete',$user->id),'method'=>'delete']) }}
						{{ Form::submit('Apagar', ['class'=>'btn btn-danger']) }}
						{{ Form::close() }}
					</td>
					
			@endforeach
		</table>
		{{ $users->appends($_GET)->links() }}
	</div>
	@else
	<div class="alert alert-warning">
		<p><i class="fa fa-marker"></i> Ainda não temos conteúdo para esta área</p>
	</div>
	@endif
</div>
@stop

app/views/admin/users/leaders.blade.php
@extends('layouts.admin')
@section('content')
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            {{ $alias }} <small>({{ $users->getTotal() }})</small>
        </h1>
    </div>
</div>
<!-- /.row -->
<div class="row" id="searchBlock">
	<div class="col-md-10">
		{{ Form::open(['route'=>'users.search', 'method'=>'get', 'class'=>'form-inline']) }}
		Filtrar por:
		{{ Form::select('state_id', [''=>'Selecione Estado']+$states, Input::get('state_id'), ['class'=>'form-control','id'=>'state_id']) }}
		{{ Form::select('city_id', [''=>'Selecione Cidade']+$cities, Input::get('city_id'), ['class'=>'form-control','id'=>'city_id']) }}
    {{ Form::select('activity', [''=>'Selecione por atividade', '0' => 'Ativo', '1'=>'Inativo'], Input::get('activity'), ['class'=>'form-control']) }}
    {{ Form::button('<i class="fa fa-search"></i> Buscar', ['class'=>'btn btn-primary','type'=>'submit']) }}
		{{ Form::close() }}
	</div>
	<div class="col-md-2">
		{{ Form::open(['route'=>'user.download.excel']) }}
		{{ Form::hidden('alias',$alias) }}
		@foreach($users_all as $u)
		{{ Form::hidden('users[]', $u->id) }}
		@endforeach
		{{ Form::button('<i class="fa fa-file-excel-o"></i> Gerar relatório', ['class'=>'btn btn-success','type'=>'submit']) }}
		{{ Form::close() }}
	</div>
</div>
<div class="col-md-12">

	@include('layouts.notifications')

	@if($users->count() > 0)
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
			<tr>
				<th>Nome</th>
				<th>Email</th>
				<th>Telefones</th>
				<th>Local</th>
				@if($alias == 'Líderes')
				<td>Último agendamento realizado</td>
				<td>Institutos de interesse</td>
				@endif
				<th>Ativo/Inativo</th>
				<th>Apagar</th>

			</tr>
			@foreach($users as $user)
				<tr>
					<td>{{ $user->userdata->username }}</td>
					<td>{{ $user->userdata->cpf }}</td>
					<td>{{ $user->userdata->cel }} | {{ $user->userdata->cel }}</td>
					<td>{{ $user->userdata->city->name }} - {{ $user->userdata->city->state->uf }}</td>
					@if($alias == 'Líderes')
					<td>
						@if($user->agendas->count()>0)
						{{ Helper::ConverterBR($user->agendas->last()->created_at) }} às {{ Helper::Hora($user->agendas->last()->created_at) }}
						@endif
					</td>
					<td>
						<ul>
							@foreach($user->institutes as $i)
								<li>{{ $i->name }}</li>
							@endforeach
						</ul>
					</td>
					@endif
					<!--<td>
						<a href="{{ route('admin.usuarios.edit', $user->id) }}"><i class="fa fa-edit"></i></a>
					</td>-->
					<td>
						@if($user->lead_inactive == '0')
							<i class="fa fa-check"></i> Ativo
						@else
							<i class="fa fa-close"></i> Inativo
						@endif
					</td>
					<td>
						{{ Form::open(['route'=>array('admin.usuarios.destroy', 'id'=>$user->id), 'method'=>'delete']) }}
						<button type="submit">
			                <i class="fa fa-trash"></i>
			            </button>

						{{ Form::close() }}
					</td>
				</tr>
			@endforeach
		</table>
		{{ $users->appends($_GET)->links() }}
	</div>
	@else
	<div class="alert alert-warning">
		<p><i class="fa fa-marker"></i> Ainda não temos conteúdo para esta área</p>
	</div>
	@endif
</div>
@stop